name: workflow3
on:
  workflow_run:
    workflows: ["workflow2"]
    types:
      - completed
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-3
        run: echo "workflow3"


        