---

name: docker
on:
  workflow_run:
    workflows: ["sonarqube"]
    types:
      - completed
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-3
        run: echo "docker"